org: mpgxc
app: infra-face-rekognition-sls
service: infra-face-rekognition-sls

configValidationMode: warn
useDotenv: true

plugins:
  - serverless-prune-plugin
  - serverless-plugin-optimize
  - serverless-deployment-bucket
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${env:AWS_REGION_DEFAULT, 'us-east-1'}
  stackName: ${self:service}-${self:provider.stage}
  deploymentBucket:
    name: ${self:service}-${self:provider.region}-deployment-bucket
    blockPublicAccess: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rekognition:DetectFaces"
        - "rekognition:IndexFaces"
        - "rekognition:ListFaces"
        - "rekognition:SearchFacesByImage"
        # Isso para o CRUD dinâmico de coleções
        - "rekognition:CreateCollection"
        - "rekognition:DeleteCollection"
        - "rekognition:ListCollections"
        # S3
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
        # DynamoDB
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:UpdateItem"
        - "dynamodb:BatchWriteItem"
        # SQS
        - "sqs:SendMessage"
        - "sqs:SendMessageBatch"
      Resource:
        - "*"

custom:
  defaultStage: dev
  prune:
    automatic: true
    number: 2
  logRetentionInDays: 7
  serverless-offline:
    allowCache: true
    useChildProcesses: true
    httpPort: 4000
  REKOGNITION_COLLECTION: ${self:service}-${self:provider.stage}-collection

layers:
  sharpLayer:
    path: layers/sharp
    name: ${self:provider.stage}-sharp
    description: A layer for the sharp package
    package:
      include:
        - node_modules/**
    compatibleRuntimes:
      - nodejs20.x
    compatibleArchitectures:
      - x86_64

functions:
  DetectAndIndexFaces:
    handler: build/handlers/picture-index-processing.handler
    memorySize: 256
    timeout: 120
    description: Detects faces and indexes them in the Rekognition collection
    maximumRetryAttempts: 0
    events:
      - sqs:
          arn: !GetAtt FaceRecognitionQueue.Arn
          batchSize: 20
          maximumBatchingWindow: 60 # Espera 60 segundos para juntar mensagens antes de chamar a função lambda
          functionResponseType: ReportBatchItemFailures # Retorna um relatório de falhas
    environment:
      REKOGNITION_COLLECTION: ${self:custom.REKOGNITION_COLLECTION}
      IMAGE_PROCESSING_FACE_EXTRACT: !Ref ImageExtractFaceQueue
      IMAGE_PROCESSING_THUMBNAIL: !Ref ImageGenerateThumbnailQueue

  ImageExtractFace:
    handler: build/handlers/image-extract-face.handler
    memorySize: 256
    timeout: 240 # 4 minutos
    description: Extracts the face from the uploaded image
    maximumRetryAttempts: 0
    events:
      - sqs:
          arn: !GetAtt ImageExtractFaceQueue.Arn
          batchSize: 1
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures
    layers:
      - { Ref: SharpLayerLambdaLayer }

  ImageThumbnailGenerator:
    handler: build/handlers/image-thumbnail-generator.handler
    memorySize: 256
    timeout: 240 # 4 minutos
    description: Generates a thumbnail for the uploaded image
    maximumRetryAttempts: 0
    events:
      - sqs:
          arn: !GetAtt ImageGenerateThumbnailQueue.Arn
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures
    layers:
      - { Ref: SharpLayerLambdaLayer }

  FindSimilarFaces:
    handler: build/handlers/picture-search.handler
    memorySize: 128
    timeout: 10
    description: Finds similar faces in the Rekognition collection
    maximumRetryAttempts: 0
    events:
      - httpApi: POST /search
    environment:
      REKOGNITION_COLLECTION: ${self:custom.REKOGNITION_COLLECTION}

  FailureNotification:
    handler: build/handlers/failure-notification.handler
    memorySize: 128
    timeout: 10
    description: Sends a notification when a message fails to be processed
    maximumRetryAttempts: 0
    events:
      - sqs:
          arn: !GetAtt FaceRecognitionQueueDLQ.Arn
          batchSize: 1
      - sqs:
          arn: !GetAtt ImageExtractFaceQueueDLQ.Arn
          batchSize: 1
      - sqs:
          arn: !GetAtt ImageGenerateThumbnailQueueDLQ.Arn
          batchSize: 1

resources:
  Resources:
    FaceRecognitionBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-bucket
        AccessControl: Private
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        # Por algum motivo esta sessão sempre tem de ser deployado por último
        NotificationConfiguration:
          QueueConfigurations:
            - Event: s3:ObjectCreated:*
              Queue: !GetAtt FaceRecognitionQueue.Arn
              Filter:
                S3Key:
                  Rules:
                    - Name: prefix
                      Value: uploads/incoming/
                    - Name: suffix
                      Value: .jpg
            - Event: s3:ObjectCreated:*
              Queue: !GetAtt FaceRecognitionQueue.Arn
              Filter:
                S3Key:
                  Rules:
                    - Name: prefix
                      Value: uploads/incoming/
                    - Name: suffix
                      Value: .jpeg

    ImageExtractFaceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-image-extract-face-queue
        VisibilityTimeout: 240
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt FaceRecognitionQueueDLQ.Arn
          maxReceiveCount: 1

    ImageExtractFaceQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-image-extract-face-queue-dlq
        VisibilityTimeout: 240

    FaceRecognitionQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-queue
        VisibilityTimeout: 240
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt FaceRecognitionQueueDLQ.Arn
          maxReceiveCount: 1

    FaceRecognitionQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-queue-dlq
        VisibilityTimeout: 240

    ImageGenerateThumbnailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-generate-thumbnail-queue
        VisibilityTimeout: 240
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ImageGenerateThumbnailQueueDLQ.Arn
          maxReceiveCount: 1

    ImageGenerateThumbnailQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-generate-thumbnail-queue-dlq
        VisibilityTimeout: 240

    FaceRecognitionQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Id: SQSQueuePolicy
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: sqs:SendMessage
              Resource: !GetAtt FaceRecognitionQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !GetAtt FaceRecognitionBucket.Arn
        Queues:
          - !Ref FaceRecognitionQueue

    FaceRecognitionCollection:
      Type: AWS::Rekognition::Collection
      Properties:
        CollectionId: ${self:service}-${self:provider.stage}-collection

    RekognitionBucketAssetsControll:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-rekognition-bucket-assets-controll
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: SK-Index
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
            Projection:
              ProjectionType: ALL

package: ${file(package.yml):package}
